# based on https://citizix.com/running-postgresql-14-with-docker-and-docker-compose/
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
     - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
