version: '3'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - mariadb_data:/var/lib/mysql
      # Bootstrap database
      # - ./dev/mariadb:/docker-entrypoint-initdb.d
    pports:
      - "3306:3306"

# set a path to store data
volumes:
  mariadb_data: /opt/database


