services:
    cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      restart: unless-stopped
      ports:
        - "9999:8978"
      volumes:
        - cloudbeaver:/opt/cloudbeaver/workspace

volumes:
  cloudbeaver:
    driver: local
