services:
   pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
       PGADMIN_DEFAULT_EMAIL: "a@b.com"
       PGADMIN_DEFAULT_PASSWORD: "password"
    # network_mode: host 
    # work on 80
    
